In [1]:
import numpy as np

In [2]:
an_array = np.array([3,33,333]) # create a a rank 1 array 
print(type(an_array)) #teh type of an ndarray is <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [3]:
# an_array.shape
print(an_array.shape)

(3,)


In [4]:
#bcoz this is a 1-rank array we need only one index to access each element   
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [5]:
an_array[0]=888 #ndarrays are mutable, here we change an element of the array 


In [6]:
an_array

array([888,  33, 333])

## 2d array

In [7]:
another = np.array([[11,12,13],[21,22,23]]) # creating 2 rank array
print(another) # 
print("The shape is 2 rows, 3 columns is", another.shape) # gives rows X columns
print("Accessing elements [0,0],[0,1],[1,0] of the array", another[0,0],",",another[0,1],",",another[1,0]) # accessing the values according to position.

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns is (2, 3)
Accessing elements [0,0],[0,1],[1,0] of the array 11 , 12 , 21


# Matrix

In [8]:
#creating matrix 2x2
ex1=np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [9]:
ex2=np.full((3,3),8.0)
print(ex2)

[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


In [10]:
ex3= np.eye(3,3)
print(ex3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
ex4 = np.ones((2,2))
print(ex4)

[[1. 1.]
 [1. 1.]]


In [12]:
print(ex4.shape) # gives shape of array 
print(ex4[0,0])# gives values at the position of[0,0]

(2, 2)
1.0


In [13]:
#random will generate random numbers
ex5 = np.random.random((2,2))
print(ex5)

[[0.42100601 0.54444497]
 [0.05085052 0.05150963]]


# Slice indexing

In [14]:
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [15]:
a_slice = an_array[0:2, 1:3] #[rows, columns]
print(a_slice)

[[12 13]
 [22 23]]


In [16]:
print("Before: ",an_array[0,1]) #check the element at 0,1
a_slice[0,0]=1000  #a_slice[0,0] is the same piece of data as an_array[0,1]
print("After: ", an_array[0,1])

Before:  12
After:  1000


In [17]:
an_array

array([[  11, 1000,   13,   14],
       [  21,   22,   23,   24],
       [  31,   32,   33,   34]])

In [18]:
# Creating the rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [19]:
# using both integer indexing and slicing generates an aray of lower rank
row_rank1 = an_array[1, :] #Rank 1 view
print(row_rank1)
row_rank1.shape  #notice the shape []

[21 22 23 24]


(4,)

In [20]:
# Sicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :] #rank 2 view
print(row_rank2)
row_rank2.shape  #notice the shape [[]]

[[21 22 23 24]]


(1, 4)

In [21]:
col_rank1 = an_array[:, 1] #rank 1 view
print(col_rank1)
col_rank1.shape

[12 22 32]


(3,)

In [22]:
col_rank2 = an_array[:, 1:2] #rank 2 view
print(col_rank2)
col_rank2.shape

[[12]
 [22]
 [32]]


(3, 1)

In [23]:
#cerate a  new array 
an_array = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43,]])
print("Original Array: ")
print(an_array)

Original Array: 
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [24]:
#create tan array of indices
col_indices= np.array([0,1,2,0])
print('\nCol indices picked: ', col_indices)

row_indices= np.arange(4) # 0,1,2,3
print('\nRows indices picekd: ',row_indices)

# row_indices= np.array([0,1,2,3]) # 0,1,2,3
# print('\nRows indices picekd: ',row_indices)


Col indices picked:  [0 1 2 0]

Rows indices picekd:  [0 1 2 3]


In [25]:
# Examine the pairings of rows and col_indices. These are the elements we'll change next.
for i,j in zip(row_indices,col_indices):  #zip: it gets two values together
    print(i,",",j)

0 , 0
1 , 1
2 , 2
3 , 0


In [26]:
#select one elementfrom each row
print('Values in the array at those indices: ', an_array[row_indices,col_indices])
#an_array[0,0],an_array[1,1],an_array[2,2]an_array[3,0]

Values in the array at those indices:  [11 22 33 41]


In [27]:
an_array[row_indices,col_indices]+=10000  #a=a+10 is same as a+=10
print('\nChanged Array: ')
print()
print(an_array)


Changed Array: 

[[10011    12    13]
 [   21 10022    23]
 [   31    32 10033]
 [10041    42    43]]


Date: 06-05-2021

In [28]:
#boolean values 
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [29]:
#create a filter which will be boolean values for whether each element meets this condition 

filter = (an_array>15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [30]:
#we can select just those values which meets that condition
print(an_array[filter])# values grater than 15


[21 22 31 32]


In [31]:
print(an_array[an_array>15])

[21 22 31 32]


In [32]:
an_array[an_array % 2 ==0]+=100
an_array

array([[ 11, 112],
       [ 21, 122],
       [ 31, 132]])

In [33]:
ex1 = np.array([11,22])
print(ex1.dtype)

int32


In [34]:
ex2 = np.array([11.0,22.00])
print(ex2.dtype)

float64


In [35]:
ex3 = np.array([11,22],dtype=np.int64)
print(ex3.dtype)

int64


In [36]:
ex4 = np.array([11.1,22.7],dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 22]


In [37]:
ex5 = np.array([11,21],dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


In [38]:
x= np.array([[111,112],[121,122]],dtype=np.int)
y= np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [39]:
#Addition of two matrix
print(x+y) 
print()
print(np.add(x,y)) #so does the numpy function "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [40]:
#subtract
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [41]:
#multipy
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [42]:
#divide
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [43]:
# sq. root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [44]:
# exponent (e**x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [45]:
#setup a random 2 x5 matrix
arr = 10*np.random.randn(2,5) # random.random or random.randn or random.randint
print(arr)

[[  8.55779168  12.43351631   4.70495433   3.21451781  -3.43289637]
 [  1.78204749   1.96761079  -0.59748524   9.08117222 -16.04901724]]


In [46]:
#compute the mean for all the elements
print(arr.mean())

2.1662211772774387


In [47]:
#compute the mean by row
print(arr.mean(axis=1))

[ 5.09557675 -0.7631344 ]


In [48]:
# compute the mean by column
print(arr.mean(axis= 0))

[ 5.16991959  7.20056355  2.05373454  6.14784501 -9.74095681]


In [49]:
#sum all the elements
print(arr.sum())

21.662211772774388


In [50]:
#compute the medians
print(np.median(arr,axis=1)) #by rows 1st and 2nd also

[4.70495433 1.78204749]


In [51]:
#create a 10 element array of randoms
unsorted= np.random.randn(10)
print(unsorted)

[-0.34885487 -0.73310018 -0.74761777  0.85451464 -1.12521044 -0.61610352
 -0.98636246  0.56465859 -0.75355791  0.04134913]


In [52]:
#create copy and sort
sorted=np.array(unsorted)
sorted.sort() #.sort function will arrange the values in acending order

print(sorted)
print()
print(unsorted)

[-1.12521044 -0.98636246 -0.75355791 -0.74761777 -0.73310018 -0.61610352
 -0.34885487  0.04134913  0.56465859  0.85451464]

[-0.34885487 -0.73310018 -0.74761777  0.85451464 -1.12521044 -0.61610352
 -0.98636246  0.56465859 -0.75355791  0.04134913]


In [53]:
#inplace sorting
unsorted.sort()
print(unsorted)

[-1.12521044 -0.98636246 -0.75355791 -0.74761777 -0.73310018 -0.61610352
 -0.34885487  0.04134913  0.56465859  0.85451464]


Finding Unique elements:

In [54]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))# it will return the unique valuses 

[1 2 4]


# Date: 10/05/2021

In [55]:
s1 = np.array(['desk',"chair",'bulb'])
s2 = np.array(['lamp',"bulb",'chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [56]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [57]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [58]:
print(np.setdiff1d(s1,s2))# elements in s1 that are not in s2

['desk']


In [59]:
print(np.in1d(s1,s2))#which elements of s1 is also in s2

[False  True  True]


Broadcasting

In [60]:
start=np.zeros([4,3])
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [61]:

add_rows = np.array([1,0,2])
print(add_rows)


[1 0 2]


In [62]:
 # add to each of 'start using broadcasting'
y= start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [63]:
#create an nd array which is 4x1 to broadcast columns
add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T #transpose: coverts rows into columns and vice versa
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [64]:
#add to each columns of 'start' using
y= start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [65]:
#this will just broadcast both dimensions
add_scalar = np.array([1])
print(start + add_scalar)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Example from the slides

In [66]:
arrA=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
arrB=[0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [68]:
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


speed test

In [69]:
from numpy import arange
from timeit import Timer


size  =1000000
timeits =1000

In [70]:
nd_array = arange(size)
print(type(nd_array))


<class 'numpy.ndarray'>


In [71]:
#timer expects the operations as parameter,
# here we pass nd_arrat.sum()
timer_numpy = Timer("nd_array.sum()","from __main__ import nd_array")

# print("Timer taken by numpy ndarray: %f seconds" % (timer_numpy.timeit(timeits/timeits))
print("Time taken by numpy ndarray: %f seconds" %(timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000885 seconds


In [72]:
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [73]:
timer_list =Timer("sum(a_list)" , "from __main__ import a_list")

print("Time taken by list:  %f seconds" %(timer_list.timeit(timeits)/timeits))

Time taken by list:  0.044842 seconds


In [74]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" %(timer_list.timeit(timeits)/timeits))

Time taken by list:  0.045115 seconds


############# Date:11/05/2021 ##############

In [90]:
x= np.array([23.23,24.24])

In [93]:
np.save('an_array',x) #save as the values in x to an_array

In [95]:
np.load('an_array.npy')

array([23.23, 24.24])

Text Format:

In [78]:

np.savetxt('array.txt', X=x, delimiter=',') #savetxt function wil store your file in text format.
np.loadtxt('array.txt',delimiter=',') #3 delimiter and sep are same which is seperated by comma.

array([23.23, 24.24])

In [79]:
#determine the inner product of two vectors 
x2d=np.array([[1,1],[1,1]])
y2d=np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [82]:
#determine the inner product of two vetors 
a1d=np.array([9,9])
b1d=np.array([10,10])

print(a1d.dot(b1d)) #9*10 + 9*10 = 180
print()
print(np.dot(a1d,b1d))

180

180


sum:


In [83]:
#sum elements in the array
ex1=np.array([[11,12],[21,22]])
print(np.sum(ex1)) #add all numbers 

66


In [84]:
print(np.sum(ex1, axis=0)) # column-wise sum

[32 34]


In [85]:
print(np.sum(ex1, axis=1)) # row-wise sum

[23 43]


In [86]:
x=np.random.randn(8)
x

array([-1.55394146, -0.0884132 ,  1.18851983,  0.59651344,  0.84814701,
       -0.72925336, -1.90175402,  0.41519195])

In [87]:
y=np.random.randn(8)
y

array([ 1.27777307,  1.14819231,  1.29154746,  0.67365915,  1.2873661 ,
       -0.18745135,  1.10713689,  1.3200205 ])

In [88]:
np.maximum(x,y)

array([ 1.27777307,  1.14819231,  1.29154746,  0.67365915,  1.2873661 ,
       -0.18745135,  1.10713689,  1.3200205 ])

### Reshape Array:

In [96]:
# grab values from 0 through 19 in an arraay
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [97]:
#reshape to be a 4x5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [100]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [102]:
ex1 = np.array([[11,12],[21,22]])
ex1.T


array([[11, 21],
       [12, 22]])

### Indexing using where():

In [107]:
x_1= np.array([1,2,3,4,5])

y_1= np.array([11,22,33,44,55])
#the working of .where is as follows.....
#where we have true in filter it wi print X-1 values and for false it wil print y_1 values
filter = np.array([True, False, True, False, True])

In [108]:
out= np.where(filter,x_1,y_1)
print(out)

[ 1 22  3 44  5]


In [109]:
mat = np.random.rand(5,5)
mat

array([[0.03331775, 0.33965862, 0.92567221, 0.29211168, 0.13127441],
       [0.84590039, 0.71783168, 0.63770842, 0.25307654, 0.2311734 ],
       [0.54991217, 0.20899558, 0.66094172, 0.76106377, 0.67782425],
       [0.21926413, 0.45330041, 0.27450501, 0.37960217, 0.18261807],
       [0.26716312, 0.71622833, 0.22814714, 0.76108209, 0.03186608]])

In [120]:
np.where( mat > 0.5,1000,-1 )


"""if mat> 0.5:
else:
    replace(-1)
    """


'if mat> 0.5:\nelse:\n    replace(-1)\n    '

any or all conditionals

In [121]:
arr_bools =  np.array([True, False, True, False, True])

In [123]:
arr_bools.any()#is any value True

True

In [124]:
arr_bools.all()#are all values True

False

In [126]:
Y= np.random.normal(size=(1,5))
print(Y)

[[-0.70997305  1.27507378 -0.43312208 -0.43993058  0.465824  ]]


In [128]:
z= np.random.randint(low=2,high=50,size=4)
print(z)#int integer values
#low for lower values and high for higher limit

[24  8 34 28]


In [129]:
np.random.permutation(z)#returns a new ordering of elements 

array([28,  8, 24, 34])

In [130]:
#type of distribution [uniform and normal]
np.random.uniform(size=4)#uniform distribution


array([0.45397522, 0.6292279 , 0.26248596, 0.09183935])

In [131]:
np.random.normal(size=4)#normal distribution

array([-0.2174341 ,  0.00556092,  0.00898573, -0.69520671])

merging :

In [134]:
k= np.random.randint(low=2,high=50,size=(2,2))
print(k)
print()
m= np.random.randint(low=2,high=50,size=(2,2))
print(m)

[[30 25]
 [43 48]]

[[ 9 19]
 [13 11]]


In [135]:
np.vstack((k,m)) #join vertically

array([[30, 25],
       [43, 48],
       [ 9, 19],
       [13, 11]])

In [136]:
np.hstack((k,m)) #join horizonntally

array([[30, 25,  9, 19],
       [43, 48, 13, 11]])

In [142]:
np.concatenate([k,m],axis=0)

array([[30, 25],
       [43, 48],
       [ 9, 19],
       [13, 11]])

In [145]:
np.concatenate([k,m.T],axis=1)

array([[30, 25,  9, 13],
       [43, 48, 19, 11]])